### ISSUE TITLE
How to upload screenshots on tesults dashboard

### ISSUE THREAD

**Issue by Rink9** [tesults/playwright-tesults-reporter#1]
Hi I was exploring tesults reporter and it seems really good to me. Appreciate!

**Problem:** I was trying to upload screenshots on tesults dashboard but somehow didn't find solution. Also on documentation there is no approaches like this.

**Things i want to achieve**

For test purpose simply i have written code for creating a screenshot and kept that screenshot on data folder. When i run this locally it creates screenshot perfectly but I want to upload this `data` folder on tesults dashboard when test cases will be executing. 

**Mainly i want to view the screenshots on tesults dashboard.** 

```
test("should validate title and description", async ({ page }) => {

    await expect(
      page.locator(".elementor-widget-heading > div > h1")
    ).toHaveText("The future of mobility is here.");
    
    await page.screenshot({ path: "data/screenshot.png" });
  });
```

**Comment by ajeetd** [comment]
Hi Rinky,

If you are using the Tesults Playwright reporter you can attach screenshots
as shown here
https://www.tesults.com/docs/playwright. Specifically, see the section
called ‘Files generated by tests’. Please get back to me if you have any
other questions or if you encounter  issues with this approach.

Ajeet

Tesults | https://www.tesults.com

**Comment by Rink9** [comment]
@ajeetd Thank you so much it worked! I forgot to add `testInfo.attach` function. Now it's generating the screenshots on files on tesults dashboard. Closing this issue.
